INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10027', 'code_gen_form_type', '表单类型', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10028', 'code_gen_query_type', '查询匹配方式', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10031', 'del_flag', '删除标记', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10039', 'show_hide', '显示/隐藏', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10045', 'sys_area_type', '区域类型', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10046', 'sys_data_scope', '数据范围', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10047', 'sys_log_type', '日志类型', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10048', 'sys_office_grade', '机构等级', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10049', 'sys_office_type', '机构类型', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10050', 'sys_user_type', '用户类型', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10054', 'user_gender', '性别', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10055', 'workflow_bind_type', '工作流绑定对象', NULL, 0);
INSERT INTO `sys_dict`(`dict_id`, `type`, `name`, `remark`, `del_flag`) VALUES ('10056', 'yes_no', '是/否', NULL, 0);

INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100074', '10027', '下拉Select', '6', 6, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100075', '10027', '富文本', '3', 3, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100076', '10027', '选择用户', '10', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100077', '10027', '单行文本', '1', 1, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100078', '10027', '单选Radio', '4', 4, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100079', '10027', '日期选择', '7', 7, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100080', '10027', '选择部门', '11', 11, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100081', '10027', '多选CheckBox', '5', 5, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100082', '10027', '时间选择', '8', 8, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100083', '10027', '文件上传', '9', 9, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100084', '10027', '多行文本', '2', 2, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100085', '10028', 'Like', '8', 8, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100086', '10028', 'Left Like', '9', 9, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100087', '10028', 'Right Like', '10', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100088', '10028', '>', '3', 3, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100089', '10028', '<', '5', 5, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100090', '10028', 'In', '11', 11, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100091', '10028', '=', '1', 1, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100092', '10028', 'Between', '7', 7, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100093', '10028', '<=', '6', 6, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100094', '10028', '!=', '2', 2, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100095', '10028', '>=', '4', 4, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100102', '10031', '删除', '1', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100103', '10031', '正常', '0', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100128', '10039', '隐藏', '0', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100129', '10039', '显示', '1', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100145', '10045', '省份、直辖市', '2', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100146', '10045', '区县', '4', 40, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100147', '10045', '国家', '1', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100148', '10045', '地市', '3', 30, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100149', '10046', '按明细设置', '9', 100, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100150', '10046', '所在部门及以下数据', '4', 40, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100151', '10046', '所有数据', '1', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100152', '10046', '仅本人数据', '8', 90, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100153', '10046', '所在公司数据', '3', 30, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100154', '10046', '所在部门数据', '5', 50, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100155', '10046', '所在公司及以下数据', '2', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100156', '10047', '异常日志', '2', 40, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100157', '10047', '接入日志', '1', 30, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100158', '10048', '四级', '4', 40, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100159', '10048', '一级', '1', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100160', '10048', '三级', '3', 30, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100161', '10048', '二级', '2', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100162', '10049', '全资子公司', '2', 90, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100163', '10049', '控股子公司', '3', 80, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100164', '10049', '部门', '4', 70, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100165', '10049', '其他', '5', 100, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100166', '10049', '分公司', '1', 60, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100167', '10050', '系统管理', '1', 10, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100168', '10050', '普通用户', '3', 30, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100169', '10050', '部门经理', '2', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100181', '10054', '男', '1', 1, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100182', '10054', '女', '2', 2, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100183', '10055', '无绑定对象', '1', 1, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100184', '10055', '角色', '2', 2, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100185', '10055', '发起人', '6', 6, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100186', '10055', '发起人所属机构', '7', 7, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100187', '10055', '发起人所属机构+角色', '8', 8, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100188', '10055', '通过代码指定', '9', 9, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100189', '10055', '机构', '3', 3, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100190', '10055', '机构+角色', '5', 5, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100191', '10055', '用户', '4', 4, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100192', '10056', '否', '0', 20, NULL);
INSERT INTO `sys_dict_data`(`data_id`, `dict_id`, `label`, `value`, `sort`, `remark`) VALUES ('100193', '10056', '是', '1', 10, NULL);
