# 邮件模板
INSERT INTO `base_template_type`(`code`, `name`) VALUES ('000', '邮件 - 消息通知');
INSERT INTO `base_template_type`(`code`, `name`) VALUES ('001', '邮件 - 注册验证码');
INSERT INTO `base_template_type`(`code`, `name`) VALUES ('002', '邮件 - 注册成功');
INSERT INTO `base_template_type`(`code`, `name`) VALUES ('003', '邮件 - 重置密码');
INSERT INTO `base_template`(`template_id`, `content`, `name`, `is_default`, `code`) VALUES ('wte3yelzpy', '<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse:collapse;background-color:#F8F8F8;\" class=\"ke-zeroborder\">\n	<tbody>\n		<tr>\n			<td>\n				&nbsp;\n			</td>\n		</tr>\n		<tr>\n			<td>\n				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\" style=\"border:1px solid #f0f0f0;border-bottom:none;\" class=\"ke-zeroborder\">\n					<tbody>\n						<tr>\n							<td align=\"center\" bgcolor=\"#70bbd9\" style=\"padding:10px 20px;color:#ffffff;font-size:28px;font-weight:bold;font-family:Arial, sans-serif;text-align:left;\">\n								{companyName}\n							</td>\n						</tr>\n					</tbody>\n				</table>\n				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\" style=\"border:1px solid #f0f0f0;border-top:none;\" class=\"ke-zeroborder\">\n					<tbody>\n						<tr>\n							<td bgcolor=\"#ffffff\" style=\"padding:40px 30px 40px 30px;\">\n								<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"ke-zeroborder\">\n									<tbody>\n										<tr>\n											<td style=\"color:#153643;font-family:Arial, sans-serif;font-size:18px;\">\n												尊敬的用户，您好：\n											</td>\n										</tr>\n										<tr>\n											<td style=\"padding:20px 0 30px 0;color:#153643;font-family:Arial, sans-serif;font-size:14px;line-height:20px;padding-left:35px;\">\n												{messageBody}\n											</td>\n										</tr>\n										<tr>\n											<td style=\"color:#153643;font-size:18px;text-align:right;\">\n												{companyName}\n											</td>\n										</tr>\n									</tbody>\n								</table>\n							</td>\n						</tr>\n					</tbody>\n				</table>\n			</td>\n		</tr>\n		<tr>\n			<td>\n				&nbsp;\n			</td>\n		</tr>\n	</tbody>\n</table>', '邮件消息模板', 1, '000');
INSERT INTO `base_template`(`template_id`, `content`, `name`, `is_default`, `code`) VALUES ('wk6gsvpuy7', '<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse:collapse;background-color:#F8F8F8;\" class=\"ke-zeroborder\">\n	<tbody>\n		<tr>\n			<td>\n				&nbsp;\n			</td>\n		</tr>\n		<tr>\n			<td>\n				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\" style=\"border:1px solid #f0f0f0;border-bottom:none;\" class=\"ke-zeroborder\">\n					<tbody>\n						<tr>\n							<td align=\"center\" bgcolor=\"#70bbd9\" style=\"padding:10px 20px;color:#ffffff;font-size:28px;font-weight:bold;font-family:Arial, sans-serif;text-align:left;\">\n								{companyName}\n							</td>\n						</tr>\n					</tbody>\n				</table>\n				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\" style=\"border:1px solid #f0f0f0;border-top:none;\" class=\"ke-zeroborder\">\n					<tbody>\n						<tr>\n							<td bgcolor=\"#ffffff\" style=\"padding:40px 30px 40px 30px;\">\n								<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"ke-zeroborder\">\n									<tbody>\n										<tr>\n											<td style=\"color:#153643;font-family:Arial, sans-serif;font-size:18px;\">\n												尊敬的用户，您好：\n											</td>\n										</tr>\n										<tr>\n											<td style=\"padding:20px 0 30px 0;color:#153643;font-family:Arial, sans-serif;font-size:14px;line-height:20px;padding-left:35px;\">\n												你此次注册的验证码是：<b>{registryCode}</b>，请在 {expireTime} 分钟内输入验证码进行下一步操作。 <br />\n如非你本人操作，请忽略此邮件。\n											</td>\n										</tr>\n										<tr>\n											<td style=\"color:#153643;font-size:18px;text-align:right;\">\n												{companyName}\n											</td>\n										</tr>\n									</tbody>\n								</table>\n							</td>\n						</tr>\n					</tbody>\n				</table>\n			</td>\n		</tr>\n		<tr>\n			<td>\n				&nbsp;\n			</td>\n		</tr>\n	</tbody>\n</table>', '注册验证码', 1, '001');
INSERT INTO `base_template`(`template_id`, `content`, `name`, `is_default`, `code`) VALUES ('wk6gsvpuy8', '<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse:collapse;background-color:#F8F8F8;\" class=\"ke-zeroborder\">\n	<tbody>\n		<tr>\n			<td>\n				&nbsp;\n			</td>\n		</tr>\n		<tr>\n			<td>\n				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\" style=\"border:1px solid #f0f0f0;border-bottom:none;\" class=\"ke-zeroborder\">\n					<tbody>\n						<tr>\n							<td align=\"center\" bgcolor=\"#70bbd9\" style=\"padding:10px 20px;color:#ffffff;font-size:28px;font-weight:bold;font-family:Arial, sans-serif;text-align:left;\">\n								{companyName}\n							</td>\n						</tr>\n					</tbody>\n				</table>\n				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\" style=\"border:1px solid #f0f0f0;border-top:none;\" class=\"ke-zeroborder\">\n					<tbody>\n						<tr>\n							<td bgcolor=\"#ffffff\" style=\"padding:40px 30px 40px 30px;\">\n								<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"ke-zeroborder\">\n									<tbody>\n										<tr>\n											<td style=\"color:#153643;font-family:Arial, sans-serif;font-size:18px;\">\n												尊敬的用户，您好：\n											</td>\n										</tr>\n										<tr>\n											<td style=\"padding:20px 0 30px 0;color:#153643;font-family:Arial, sans-serif;font-size:14px;line-height:20px;padding-left:35px;\">\n												你此次重置密码的验证码是：<b>{registryCode}</b>，请在 {expireTime} 分钟内输入验证码进行下一步操作。 <br />\n如非你本人操作，请忽略此邮件。\n											</td>\n										</tr>\n										<tr>\n											<td style=\"color:#153643;font-size:18px;text-align:right;\">\n												{companyName}\n											</td>\n										</tr>\n									</tbody>\n								</table>\n							</td>\n						</tr>\n					</tbody>\n				</table>\n			</td>\n		</tr>\n		<tr>\n			<td>\n				&nbsp;\n			</td>\n		</tr>\n	</tbody>\n</table>', '重置密码验证码', 1, '003');

# 消息
INSERT INTO `msg_type`(`msg_type_code`, `msg_type_name`) VALUES ('1', '系统');
INSERT INTO `msg_channel`(`channel_id`, `channel_name`) VALUES ('1', '系统消息');
INSERT INTO `msg_channel`(`channel_id`, `channel_name`) VALUES ('2', '系统弹窗');
INSERT INTO `msg_channel`(`channel_id`, `channel_name`) VALUES ('3', '短信');
INSERT INTO `msg_channel`(`channel_id`, `channel_name`) VALUES ('4', '邮箱');
INSERT INTO `msg_channel`(`channel_id`, `channel_name`) VALUES ('5', '公众号');
INSERT INTO `msg_template`(`template_id`, `title`, `status`, `content`, `msg_type_code`) VALUES ('10010', '审核事项通知', NULL, '您有一个{{auditType}}（{{businessName}}）申请需要审核。', '1');
INSERT INTO `msg_template`(`template_id`, `title`, `status`, `content`, `msg_type_code`) VALUES ('10011', '审核结果通知', NULL, '您的{{auditType}}（{{businessName}}）申请已经审核通过。', '1');
INSERT INTO `msg_template`(`template_id`, `title`, `status`, `content`, `msg_type_code`) VALUES ('10012', '审核结果通知', NULL, '您的{{auditType}}（{{businessName}}）申请被驳回，原因如下：{{auditRemark}}。', '1');
INSERT INTO `msg_template`(`template_id`, `title`, `status`, `content`, `msg_type_code`) VALUES ('30000', '注册成功', NULL, '恭喜您，注册成功，欢迎使用！', '1');
INSERT INTO `msg_template_channel`(`channel_id`, `template_id`) VALUES ('1', '10010');
INSERT INTO `msg_template_channel`(`channel_id`, `template_id`) VALUES ('1', '10011');
INSERT INTO `msg_template_channel`(`channel_id`, `template_id`) VALUES ('1', '10012');
INSERT INTO `msg_template_channel`(`channel_id`, `template_id`) VALUES ('1', '30000');