INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('1', '1', '0', '0,', '100000', '顶级节点', 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('2', '1', '1', '0,1,', '100002', '北京省分公司', 2, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('21', '110101', '2', '0,1,2,', '100005', '技术部', 1, 0, '', '', NULL, NULL, '', '', '', '', '{\"fileFeeBankName\":\"\",\"fileFeeBankAccount\":\"\",\"fileFeeBankUserName\":\"\",\"promiseFeeBankName\":\"\",\"promiseFeeBankAccount\":\"\",\"promiseFeeBankUserName\":\"\"}');
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('22', '110101', '2', '0,1,2,', '100003', '市场部', 1, 0, '', '', NULL, NULL, '', '', '', '', '{\"fileFeeBankName\":\"\",\"fileFeeBankAccount\":\"\",\"fileFeeBankUserName\":\"\",\"promiseFeeBankName\":\"\",\"promiseFeeBankAccount\":\"\",\"promiseFeeBankUserName\":\"\"}');
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('23', '110101', '2', '0,1,2,', '100002', '研发部', 1, 0, '', '', NULL, NULL, '', '', '', '', '{\"fileFeeBankName\":\"\",\"fileFeeBankAccount\":\"\",\"fileFeeBankUserName\":\"\",\"promiseFeeBankName\":\"\",\"promiseFeeBankAccount\":\"\",\"promiseFeeBankUserName\":\"\"}');
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('3', '1', '1', '0,1,', '100003', '湖南省分公司', 2, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('4', '1', '1', '0,1,', '100004', '浙江省分公司', 2, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('5', '1', '1', '0,1,', '100005', '东北省分公司', 2, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_office`(`id`, `area_id`, `parent_id`, `parent_ids`, `code`, `name`, `type`, `del_flag`, `address`, `zip_code`, `master_id`, `level`, `phone`, `fax`, `email`, `remarks`, `other_info`) VALUES ('6', '1', '1', '0,1,', '200000', '山东省分公司', 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `user_info`(`user_id`, `account`, `name`, `password`, `type`, `create_ip`, `create_time`, `last_login_ip`, `last_login_time`, `status`, `gender`, `birthday`, `identity_number`) VALUES ('0', '系统', '系统', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `user_info`(`user_id`, `account`, `name`, `password`, `type`, `create_ip`, `create_time`, `last_login_ip`, `last_login_time`, `status`, `gender`, `birthday`, `identity_number`) VALUES ('1', 'superadmin', '超级管理员', '1a053ec42409c4e84623848c378bf3451de94b718f8f44d399cb75e1', 1, NULL, '2017-04-21 22:15:02', '127.0.0.1', '2017-05-23 10:58:56', 1, NULL, NULL, NULL);
INSERT INTO `user_info`(`user_id`, `account`, `name`, `password`, `type`, `create_ip`, `create_time`, `last_login_ip`, `last_login_time`, `status`, `gender`, `birthday`, `identity_number`) VALUES ('2', 'admin', '管理员', '1a053ec42409c4e84623848c378bf3451de94b718f8f44d399cb75e1', 1, NULL, '2017-04-17 21:04:43', '218.76.8.17', '2018-08-31 18:08:01', 1, NULL, NULL, '430181199505022653');
INSERT INTO `user_manager`(`user_id`, `office_id`, `remark`, `work_number`, `leader_id`) VALUES ('1', '3', NULL, '100001', NULL);
INSERT INTO `user_manager`(`user_id`, `office_id`, `remark`, `work_number`, `leader_id`) VALUES ('2', '3', NULL, '100002', NULL);
INSERT INTO `user_contact_info`(`user_id`, `area_code`, `mobile`, `email`, `phone`, `wechat_id`, `address`, `zip_code`) VALUES ('1', NULL, '13800000000', 'lcw2004@163.com', '010-11111111', NULL, NULL, NULL);
INSERT INTO `user_contact_info`(`user_id`, `area_code`, `mobile`, `email`, `phone`, `wechat_id`, `address`, `zip_code`) VALUES ('2', NULL, '13822222222', 'lcw2004@163.com', '010-22222222', NULL, NULL, NULL);
INSERT INTO `user_education_info`(`user_id`, `last_education`, `last_school`, `study_profession`, `graduation_time`, `work_start_time`, `work_profession`, `work_resume`, `graduation_certificate`, `political_status`) VALUES ('1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `user_education_info`(`user_id`, `last_education`, `last_school`, `study_profession`, `graduation_time`, `work_start_time`, `work_profession`, `work_resume`, `graduation_certificate`, `political_status`) VALUES ('2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `sys_user_role`(`user_id`, `role_id`) VALUES ('2', '2');
INSERT INTO `sys_user_role`(`user_id`, `role_id`) VALUES ('1', '2');