<!DOCTYPE html>
<html lang="en">

<body>
    <h1>${message}</h1>

    12313333333


    <p><a href="${springUrl}">URL generated by Spring</a></p>
    <p><a href="${url}">URL generated by JSTL</a></p>
</body>

</html>